# Generated by Django 5.1.3 on 2024-12-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='duagnosis_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
