# Generated by Django 5.1.3 on 2024-12-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0002_diagnosis_duagnosis_confidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='duagnosis_confidence',
            new_name='diagnosis_confidence',
        ),
    ]
