# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1  # Ensure you have one replica for MySQL
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306  # Default MySQL port
          env:
            - name: MYSQL_DATABASE
              value: Healthcare  # Updated database name
            - name: MYSQL_USER
              value: fakhreddine  # Updated database user
            - name: MYSQL_PASSWORD
              value: sakhri  # Updated database password
            - name: MYSQL_ROOT_PASSWORD
              value: "sakhri"  # Updated root password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: db  # Use 'db' as the service name
spec:
  ports:
    - port: 3306  # MySQL default port
      targetPort: 3306
  selector:
    app: mysql
